export const uid=()=>crypto.randomUUID();
export const now=()=>new Date().toISOString();
export const round=(value,places=3)=>Math.round((Number(value)+Number.EPSILON)*10**places)/10**places;
export const number=value=>new Intl.NumberFormat('fa-IR',{maximumFractionDigits:3}).format(Number(value)||0);
let currency='تومان';
export const setCurrency=value=>{currency=String(value||'تومان')};
export const money=value=>`${new Intl.NumberFormat('fa-IR',{maximumFractionDigits:0}).format(Number(value)||0)} ${currency}`;
export const date=value=>value?new Intl.DateTimeFormat('fa-IR-u-ca-persian',{year:'numeric',month:'short',day:'numeric'}).format(new Date(value)):'—';
export const escape=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
export const unitLabels={g:'گرم',kg:'کیلوگرم',ml:'میلی‌لیتر',l:'لیتر',piece:'عدد',pack:'بسته',bottle:'بطری',can:'قوطی'};
export const units=Object.entries(unitLabels).map(([id,name])=>({id,name,group:['g','kg'].includes(id)?'mass':['ml','l'].includes(id)?'volume':id,factor:{g:1,kg:1000,ml:1,l:1000}[id]||1}));
export function toBase(quantity,unit,itemUnit){const source=units.find(x=>x.id===unit),target=units.find(x=>x.id===itemUnit);if(!source||!target||source.group!==target.group)throw new Error('واحد انتخابی با واحد پایهٔ کالا سازگار نیست.');return round(Number(quantity)*source.factor/target.factor);}
export function requirePositive(value,label){const n=Number(value);if(!Number.isFinite(n)||n<=0)throw new Error(`${label} باید بزرگ‌تر از صفر باشد.`);return n}
export function recipeNeeds(ingredients,portions,baseServings,items){requirePositive(portions,'تعداد نفرات');requirePositive(baseServings,'تعداد پایهٔ دستور پخت');const needs=new Map();for(const ingredient of ingredients){const item=items.find(x=>x.id===ingredient.itemId);if(!item)throw new Error('یکی از مواد دستور پخت در انبار پیدا نشد.');const qty=toBase(requirePositive(ingredient.quantity,'مقدار ماده')*Number(portions)/Number(baseServings)*Number(ingredient.factor||1),ingredient.unit,item.unit);needs.set(item.id,round((needs.get(item.id)||0)+qty))}return needs}
export function planNeeds(planItems,recipes,ingredients,items){const total=new Map();for(const line of planItems){const recipe=recipes.find(x=>x.id===line.recipeId);if(!recipe)throw new Error('یکی از غذاهای برنامه دستور پخت ندارد.');const lines=ingredients.filter(x=>x.recipeId===recipe.id);if(!lines.length)throw new Error(`دستور پخت «${recipe.name}» ماده‌ای ندارد.`);for(const [id,qty] of recipeNeeds(lines,line.portions,recipe.servings,items))total.set(id,round((total.get(id)||0)+qty))}return total}
export function shortageRows(needs,items){return [...needs].map(([id,required])=>{const item=items.find(x=>x.id===id);return {item,required,available:Number(item?.stock||0),shortage:round(Math.max(0,required-Number(item?.stock||0)))}}).filter(x=>x.shortage>0)}
export function suggestions(items,forecast=new Map()){return items.filter(x=>x.active!==false).map(item=>{const stock=Number(item.stock||0),required=Number(forecast.get(item.id)||0),shortage=Math.max(0,required-stock),threshold=Number(item.reorder||item.minimum||0),target=Math.max(Number(item.maximum||0),threshold,required);const suggested=stock<=threshold||shortage>0?round(Math.max(0,target-stock)):0;return {item,stock,required,shortage:round(shortage),suggested,estimated:round(suggested*Number(item.lastPrice||0),0)}}).filter(x=>x.suggested>0||x.shortage>0)}
export function validateItem(input){if(!input.name?.trim())throw new Error('نام ماده را وارد کنید.');if(!input.code?.trim())throw new Error('کد کالا را وارد کنید.');for(const key of ['minimum','reorder','maximum'])if(Number(input[key])<0)throw new Error('حدهای موجودی نمی‌توانند منفی باشند.');if(Number(input.maximum)>0&&Number(input.maximum)<Number(input.minimum))throw new Error('حداکثر پیشنهادی باید از حداقل بیشتر باشد.')}
export async function hashPassword(password,salt){const material=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);const digest=await crypto.subtle.deriveBits({name:'PBKDF2',salt:new TextEncoder().encode(salt),iterations:150000,hash:'SHA-256'},material,256);return Array.from(new Uint8Array(digest),x=>x.toString(16).padStart(2,'0')).join('')}
