import {date,unitLabels} from './domain.js';

const encoder=new TextEncoder();
const xml=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const alpha=n=>{let result='';for(n++;n;n=Math.floor((n-1)/26))result=String.fromCharCode(65+(n-1)%26)+result;return result};
function sheet(rows){const body=rows.map((row,r)=>`<row r="${r+1}">${row.map((value,c)=>{const ref=`${alpha(c)}${r+1}`;return typeof value==='number'&&Number.isFinite(value)?`<c r="${ref}"><v>${value}</v></c>`:`<c r="${ref}" t="inlineStr"><is><t>${xml(value)}</t></is></c>`}).join('')}</row>`).join('');return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView rightToLeft="1" workbookViewId="0"/></sheetViews><sheetData>${body}</sheetData></worksheet>`}
const u16=(arr,n)=>{arr.push(n&255,(n>>>8)&255)};
const u32=(arr,n)=>{arr.push(n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255)};
function crc32(bytes){let crc=-1;for(const byte of bytes){crc^=byte;for(let i=0;i<8;i++)crc=(crc>>>1)^(-(crc&1)&0xedb88320)}return(crc^-1)>>>0}
function zip(files){const local=[],central=[];let offset=0;for(const [name,content] of files){const filename=encoder.encode(name),bytes=encoder.encode(content),crc=crc32(bytes),header=[];u32(header,0x04034b50);u16(header,20);u16(header,0);u16(header,0);u16(header,0);u16(header,0);u32(header,crc);u32(header,bytes.length);u32(header,bytes.length);u16(header,filename.length);u16(header,0);local.push(new Uint8Array(header),filename,bytes);const entry=[];u32(entry,0x02014b50);u16(entry,20);u16(entry,20);u16(entry,0);u16(entry,0);u16(entry,0);u16(entry,0);u32(entry,crc);u32(entry,bytes.length);u32(entry,bytes.length);u16(entry,filename.length);u16(entry,0);u16(entry,0);u16(entry,0);u16(entry,0);u32(entry,0);u32(entry,offset);central.push(new Uint8Array(entry),filename);offset+=header.length+filename.length+bytes.length}const centralSize=central.reduce((n,x)=>n+x.length,0),end=[];u32(end,0x06054b50);u16(end,0);u16(end,0);u16(end,files.length);u16(end,files.length);u32(end,centralSize);u32(end,offset);u16(end,0);return new Blob([...local,...central,new Uint8Array(end)],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'})}
export function workbook(name,tabs){const names=tabs.map(([title])=>title.slice(0,31).replace(/[\\/*?:\[\]]/g,''));const files=[['[Content_Types].xml',`<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>${tabs.map((_,i)=>`<Override PartName="/xl/worksheets/sheet${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join('')}</Types>`],['_rels/.rels','<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>'],['xl/workbook.xml',`<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>${names.map((title,i)=>`<sheet name="${xml(title)}" sheetId="${i+1}" r:id="rId${i+1}"/>`).join('')}</sheets></workbook>`],['xl/_rels/workbook.xml.rels',`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${tabs.map((_,i)=>`<Relationship Id="rId${i+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${i+1}.xml"/>`).join('')}</Relationships>`],...tabs.map(([,rows],i)=>[`xl/worksheets/sheet${i+1}.xml`,sheet(rows)])];download(zip(files),`${name}.xlsx`)}
export function download(blob,filename){const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=filename;link.click();setTimeout(()=>URL.revokeObjectURL(url),30000)}
export function exportData(data,kind='all'){const item=id=>data.items.find(x=>x.id===id)?.name||'—',supplier=id=>data.suppliers.find(x=>x.id===id)?.name||'—',recipe=id=>data.recipes.find(x=>x.id===id)?.name||'—';const tabs={inventory:['انبار',[['کد','ماده','دسته','واحد پایه','موجودی','حداقل','نقطه سفارش','حداکثر','آخرین قیمت','میانگین قیمت'],...data.items.map(x=>[x.code,x.name,data.categories.find(c=>c.id===x.categoryId)?.name||'',unitLabels[x.unit]||x.unit,Number(x.stock||0),Number(x.minimum||0),Number(x.reorder||0),Number(x.maximum||0),Number(x.lastPrice||0),Number(x.averagePrice||0)])]],transactions:['تراکنش‌ها',[['تاریخ','ماده','نوع','مقدار','واحد','قبل','بعد','مرجع'],...data.transactions.map(x=>[date(x.createdAt),item(x.itemId),x.type,Number(x.quantity),unitLabels[x.unit]||x.unit,Number(x.before),Number(x.after),x.sourceType||''])]],purchases:['خریدها',[['شماره','تاریخ','فروشنده','وضعیت','تخفیف','مالیات'],...data.purchases.map(x=>[x.number,x.date,supplier(x.supplierId),x.status,Number(x.discount||0),Number(x.tax||0)])]],purchaseItems:['اقلام خرید',[['شماره خرید','ماده','مقدار','واحد','قیمت واحد'],...data.purchaseItems.map(x=>[data.purchases.find(p=>p.id===x.purchaseId)?.number||'',item(x.itemId),Number(x.quantity),unitLabels[x.unit]||x.unit,Number(x.unitPrice)])]],recipes:['دستور پخت',[['غذا','تعداد پایه','ماده','مقدار','واحد','ضریب'],...data.recipeIngredients.map(x=>[recipe(x.recipeId),Number(data.recipes.find(r=>r.id===x.recipeId)?.servings||0),item(x.itemId),Number(x.quantity),unitLabels[x.unit]||x.unit,Number(x.factor||1)])]],mealPlans:['برنامه غذایی',[['تاریخ','وعده','غذا','نفرات','وضعیت'],...data.mealPlanItems.map(x=>{const p=data.mealPlans.find(p=>p.id===x.planId);return[p?.date||'',x.meal,recipe(x.recipeId),Number(x.portions),p?.status||'']})]],suppliers:['فروشندگان',[['نام','تلفن','توضیحات'],...data.suppliers.map(x=>[x.name,x.phone||'',x.note||''])]],prices:['تاریخچه قیمت',[['تاریخ','ماده','قیمت','واحد'],...data.priceHistory.map(x=>[x.date,item(x.itemId),Number(x.price),unitLabels[x.unit]||x.unit])]]};const selected=kind==='all'?Object.values(tabs):[tabs[kind]].filter(Boolean);workbook(`rahnama-${kind}-${new Date().toISOString().slice(0,10)}`,selected)}
